# Generated by Django 5.1.2 on 2024-10-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=200)),
                ("transaction_id", models.CharField(max_length=200)),
                ("amount", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
            ],
        ),
    ]
